# Generated by Django 4.2.16 on 2025-09-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0019_alter_admissao_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '📊 Relatório RH',
                'verbose_name_plural': '📊 Relatório RH',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='admissao',
            name='senha_gov',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Senha Gov'),
        ),
    ]
