# Generated by Django 4.2.16 on 2025-09-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0020_relatoriorh_alter_admissao_senha_gov'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caju',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('nome_completo', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data do cadastro')),
            ],
            options={
                'verbose_name': 'Caju',
                'verbose_name_plural': 'Cajus',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
