# Generated by Django 4.2.16 on 2026-10-07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rh", "0021_caju"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="admissao",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="admissao",
            name="agencia",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d+$", "Apenas números são permitidos."
                    )
                ],
                verbose_name="Agência",
            ),
        ),
        migrations.AlterField(
            model_name="admissao",
            name="codigo",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                verbose_name="Código RCA",
            ),
        ),
        migrations.AlterField(
            model_name="admissao",
            name="conta",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d+$", "Apenas números são permitidos."
                    )
                ],
                verbose_name="Conta",
            ),
        ),
        migrations.AlterField(
            model_name="admissao",
            name="cpf",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=14,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d+$", "Apenas números são permitidos."
                    )
                ],
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="admissao",
            name="fone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d+$", "Apenas números são permitidos."
                    )
                ],
                verbose_name="Telefone",
            ),
        ),
        migrations.AlterField(
            model_name="admissao",
            name="operacao",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d+$", "Apenas números são permitidos."
                    )
                ],
                verbose_name="Operação",
            ),
        ),
        migrations.AlterField(
            model_name="caju",
            name="cpf",
            field=models.CharField(
                max_length=14,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d+$", "Apenas números são permitidos."
                    )
                ],
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="caju",
            name="telefone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d+$", "Apenas números são permitidos."
                    )
                ],
                verbose_name="Telefone",
            ),
        ),
        migrations.AlterField(
            model_name="distrato",
            name="cpf",
            field=models.CharField(
                blank=True,
                max_length=14,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d+$", "Apenas números são permitidos."
                    )
                ],
                verbose_name="CPF",
            ),
        ),
        migrations.AddConstraint(
            model_name="admissao",
            constraint=models.UniqueConstraint(
                condition=~models.Q(codigo=""),
                fields=("codigo", "data_admissao"),
                name="rh_admissao_codigo_data_admissao_preenchidos_uniq",
            ),
        ),
    ]
