# Generated by Django 4.2.16 on 2026-10-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rh", "0022_alter_admissao_codigo_opcional"),
    ]

    operations = [
        migrations.CreateModel(
            name="SsoTokenConsumido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jti_hash",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        verbose_name="Hash do identificador",
                    ),
                ),
                (
                    "expira_em",
                    models.DateTimeField(db_index=True, verbose_name="Expira em"),
                ),
                (
                    "consumido_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Consumido em"),
                ),
                (
                    "usuario_ecossistema",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Usuário do Ecossistema",
                    ),
                ),
                (
                    "login_destino",
                    models.CharField(max_length=150, verbose_name="Login de destino"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token SSO consumido",
                "verbose_name_plural": "Tokens SSO consumidos",
            },
        ),
    ]
